[placeholders]
include_app = { prompt = "Generate app?", choices = [
    "Yes",
    "No",
], default = "Yes", type = "string" }
include_adapter = { prompt = "Generate adapter?", choices = [
    "Yes",
    "No",
], default = "Yes", type = "string" }

[conditional.'include_app == "Yes"'.placeholders]
app_name = { prompt = "Enter app name", default = "my_app", type = "string" }

[conditional.'include_adapter == "Yes"'.placeholders]
adapter_name = { prompt = "Enter adapter name", default = "my_adapter", type = "string" }
