[template]
ignore = [".github", "artifacts", "target"]
exclude = ["justfile"]

[hooks]
post = ["post-script.rhai"]

[placeholders]
include_app = { prompt = "Include App Module", default = true, type = "bool" }
include_adapter = { prompt = "Include Adapter Module", default = true, type = "bool" }
include_standalone = { prompt = "Include Standalone Module", default = true, type = "bool" }

[conditional.'include_app'.placeholders]
app_name = { prompt = "Enter App Name", default = "my_app", type = "string" }

[conditional.'include_adapter'.placeholders]
adapter_name = { prompt = "Enter Adapter Name", default = "my_adapter", type = "string" }

[conditional.'include_standalone'.placeholders]
standalone_name = { prompt = "Enter Standalone Name", default = "my_standalone", type = "string" }

# Ignore files if not included
[conditional.'!include_app']
ignore = ["contracts/{{app_name}}"]
[conditional.'!include_adapter']
ignore = ["contracts/{{adapter_name}}"]
[conditional.'!include_standalone']
ignore = ["contracts/{{standalone_name}}"]
