/**
* This file was automatically generated by @abstract-money/ts-codegen@0.35.4.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @abstract-money/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Template.types";
import * as _1 from "./Template.client";
import * as _2 from "./Template.client";
import * as _3 from "./Template.message-composer";
import * as _4 from "./Template.message-builder";
export namespace contracts {
  export const Template = { ..._0,
    ..._1,
    ..._2,
    ..._3,
    ..._4
  };
}