// @ts-nocheck
          /**
* This file was automatically generated by @abstract-money/ts-codegen@0.35.8.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @abstract-money/ts-codegen generate command to regenerate this file.
*/

import { Uint64, InstantiateMsg, Pair, ExecuteMsg, Binary, EvmMsgForString, HexBinary, Uint128, CallbackRequest, QueryMsg, Callback, ResultOfExecutionResponseOrString, SentPacketData, Msg, AckInfosResponse, AckInfo, ExecutionResponse, ExecuteResult, Packet, NullableString, NullablePair } from "./EvmNote.types";
import { CamelCasedProperties } from "type-fest";
export abstract class EvmNoteExecuteMsgBuilder {
static execute = ({
  callback,
  msgs,
  timeoutSeconds
}: CamelCasedProperties<Extract<ExecuteMsg, {
  execute: unknown;
}>["execute"]>): ExecuteMsg => {
  return {
    execute: ({
      callback,
      msgs,
      timeout_seconds: timeoutSeconds
    } as const)
  };
};
}
export abstract class EvmNoteQueryMsgBuilder {
static remoteAddress = ({
  localAddress
}: CamelCasedProperties<Extract<QueryMsg, {
  remote_address: unknown;
}>["remote_address"]>): QueryMsg => {
  return {
    remote_address: ({
      local_address: localAddress
    } as const)
  };
};
static ackInfos = ({
  limit,
  startAfter
}: CamelCasedProperties<Extract<QueryMsg, {
  ack_infos: unknown;
}>["ack_infos"]>): QueryMsg => {
  return {
    ack_infos: ({
      limit,
      start_after: startAfter
    } as const)
  };
};
}