/**
* This file was automatically generated by @abstract-money/ts-codegen@0.35.8.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @abstract-money/ts-codegen generate command to regenerate this file.
*/

export type Uint64 = string;
export interface InstantiateMsg {
  block_max_gas: Uint64;
  pair?: Pair | null;
}
export interface Pair {
  connection_id: string;
  remote_port: string;
}
export type ExecuteMsg = {
  execute: {
    callback?: CallbackRequest | null;
    msgs: EvmMsgForString[];
    timeout_seconds: Uint64;
  };
};
export type Binary = string;
export type EvmMsgForString = {
  call: {
    allow_failure?: boolean | null;
    data: HexBinary;
    to: string;
    value?: Uint128 | null;
  };
} | {
  delegate_call: {
    allow_failure?: boolean | null;
    data: HexBinary;
    to: string;
    value?: Uint128 | null;
  };
};
export type HexBinary = string;
export type Uint128 = string;
export interface CallbackRequest {
  msg: Binary;
  receiver: string;
}
export type QueryMsg = "active_channel" | "pair" | {
  remote_address: {
    local_address: string;
  };
} | "block_max_gas" | {
  ack_infos: {
    limit?: number | null;
    start_after?: number | null;
  };
};
export type Callback = {
  execute: ResultOfExecutionResponseOrString;
} | {
  fatal_error: string;
};
export type ResultOfExecutionResponseOrString = {
  Ok: ExecutionResponse;
  [k: string]: unknown;
} | {
  Err: string;
  [k: string]: unknown;
};
export type SentPacketData = {
  binary: HexBinary;
} | {
  request: Packet;
};
export type Msg = {
  execute: {
    msgs: EvmMsgForString[];
  };
};
export interface AckInfosResponse {
  acks: [number, AckInfo][];
}
export interface AckInfo {
  height: number;
  index?: number | null;
  result: Callback;
  sent: SentPacketData;
}
export interface ExecutionResponse {
  executed_by: string;
  result: ExecuteResult[];
}
export interface ExecuteResult {
  data: HexBinary;
  success: boolean;
}
export interface Packet {
  msg: Msg;
  sender: string;
}
export type NullableString = string | null;
export type NullablePair = Pair | null;