[package]
name = "my-package"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
interface = ["dep:abstract-interface", "dep:cw-orch"]

[dependencies]
abstract-sdk = { workspace = true }
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }
abstract-app = { workspace = true }
abstract-std = { workspace = true }
abstract-adapter = { workspace = true }
cw-orch = { workspace = true, optional = true }
abstract-interface = { workspace = true, optional = true }
thiserror = { workspace = true }
cw-asset = { workspace = true }
cw-controllers = { workspace = true }
const_format = { workspace = true }
