permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
name: test
jobs:
  required:
    runs-on: ubuntu-latest
    name: ubuntu / ${{ matrix.toolchain }}
    strategy:
      matrix:
        toolchain: [stable, beta]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: install cargo-generate
        run: cargo install cargo-generate --locked
      - name: cargo test
        run: |
          CARGO_GENERATE_TEST_CMD="cargo test --all-features --all-targets" \
          cargo generate -d include_app=true -d include_adapter=true -d app_name=my_app -d adapter_name=my_adapter --test
